covid19helplineinfoproject/covid19helplineinfoapp/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = 'covid19helplineinfoapp'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.home, name='home'),
    path('getpeoplearound/', views.get_people_around_my_area, name='get_people_around_my_area'),
    path('persondetails', views.person_details, name='persondetails'),
    path('mylocalinfofilter',views.mylocalinfofilter,name='mylocalinfofilter'),
    path('mylocalinfo/', views.mylocalinfo, name='mylocalinfo'),
    path('mylocalinfoform/', views.mylocalinfoform, name='mylocalinfoform'),
    path('loaddata/', views.loaddata,name="loaddata"),
    path('signup/', views.signup, name='signup'),

    path('signup/account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

covid19helplineinfoproject/covid19helplineinfoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('covid19helplineinfoapp.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

covid19helplineinfoproject/covid19helplineinfoapp/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.forms.models import BaseInlineFormSet, inlineformset_factory

from django.forms import ModelChoiceField
from .models import Profile, LocalHelpInfo, HELP_TYPE

class SignUpForm(UserCreationForm):
    help_type = forms.ChoiceField(
        required=False,
      
        choices=HELP_TYPE
    )
   
    first_name = forms.CharField(max_length=30, required=True, help_text="Optional.")
    last_name = forms.CharField(max_length=30, required=True, help_text="Optional.")
    email = forms.EmailField(
        max_length=254, help_text="Required a valid email address."
    )
    # birth_date = forms.DateField(help_text="Required. Format: YYYY-MM-DD")
  
    lng = forms.DecimalField()
    lat = forms.DecimalField()
    district = forms.CharField()
    state = forms.CharField()
    country = forms.CharField()
    address = forms.CharField()
    help_text = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = User
        fields = (
            "help_type",
            "help_text",
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )


CATEGORIES = (
    ("IST", "Indian Standard Time"),
    ("CET", "Central European Time"),
    ("GMT", "Greenwich Meridian Time"),
    ("UTC", "Coordinated Universal Time"),
)


class ProfileForm(forms.ModelForm):
    time_zone = forms.ChoiceField(
        initial="CAR",
        label="Time Zone",
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=CATEGORIES,
    )

    class Meta:
        model = Profile
        fields = ( "city","state", "country", "zip_code", "bio", "profile_pic")


class LocalHelpInfoForm(forms.ModelForm):
  

    class Meta:
        model = LocalHelpInfo
        fields = ('city' ,    'state' ,    'country' ,    'zip_code',    'helpline_phonenumber1',    'helpline_phonenumber2' ,    'helpline_phonenumber3',    'helpline_whatsapp_phonenumber',    'helpline_email',    'helpline_centre_address',    'howto_get_there',   'other_instructions' ,    'map_location_url',    'info_source' 
)

covid19helplineinfoproject/covid19helplineinfoapp/views.py
import datetime
from decimal import Decimal

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from django.conf import settings

from django.http import JsonResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token

from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.db.models import Q

from django.db.models.functions import TruncMonth
from django.db.models.functions import ExtractMonth
from django.db.models import Avg, Count, Min, Sum

# from .models import

from .forms import SignUpForm, ProfileForm, LocalHelpInfoForm


from .models import (
    Profile,
    LocalHelpInfo,
    News,
    Dashboard,
    LoadDataModel,

    get_location_data,
    get_people_around,
    get_people_around_anon

)



def index(request):
    return render(request,'covid19helplineinfoapp/index.html',context={})

def home(request):
    context = {
        'local_help_circle' : True,
        'my_local_area_selected' : True
    }

    news = News.objects.all()

    dashboard = Dashboard.objects.all()[0] if len(Dashboard.objects.all()) > 0 else None
    context['news'] = news
    context['dashboard'] = dashboard
   
    print(settings.GMAP_API_KEY)
    context['GMAP_API_KEY'] = settings.GMAP_API_KEY

    return render(request,'covid19helplineinfoapp/home.html',context=context)

def get_people_around_my_area(request):
 
    current_lat = Decimal(request.GET['lat'])
    current_lng = Decimal(request.GET['lng'])
    context = {}
    if request.user and len(Profile.objects.filter(user__username=request.user))> 0:
        profile_instance = Profile.objects.filter(user__username=request.user)[0]
        people_around = get_people_around(profile_instance.id)
        print(profile_instance.id)
        print(people_around)
        context['people_around'] = people_around
    else:
        people_around = get_people_around_anon(current_lat,current_lng)
        print(people_around)
        context['people_around'] = people_around
    print(context)
    return JsonResponse(context)

@login_required
def person_details(request):
    id = request.GET.get('id')
    profile_instance = Profile.objects.get(pk=id)
    context = {'profile_instance' : profile_instance}
    return render(request,'covid19helplineinfoapp/persondetails.html', context)

    
def mylocalinfo(request):
    country = request.GET.get('country')
    state = request.GET.get('state')
    # city = request.GET.get('city')
    print('==========')
    print(country,state)
    if country and state :       
        print('country found',request.GET.get('country'))
        info = LocalHelpInfo.objects.filter(country=country,state=state)[0]
        context = {'info' : info }
        return render(request,'covid19helplineinfoapp/mylocalinfodetail.html',context=context)

    context = {
        'local_help_circle' : True,
        'my_local_area_selected' : True
    }

    result = get_location_data(None,None)
    print(result)
    context[result['location']] = result['result']


    return render(request,'covid19helplineinfoapp/mylocalinfo.html',context=context)


def mylocalinfofilter(request):

    if request.method == 'POST':
        country = request.POST.get('country')
        state = request.POST.get('state')
        # city = request.POST.get('city')
        location_data = get_location_data(country,state)
        print(location_data)
        options ='<option>Select One</option>'
        
        if request.POST.get('state'):
            res = location_data['result']
            for r in res:
                print(res)
                options += '<option value="{}">{}</option>'.format(r['city'],r['city'])
            return HttpResponse(options)
        elif request.POST.get('country'):
            res = location_data['result']
            for r in res:
                print(res)
                options += '<option value="{}">{}</option>'.format(r['state'],r['state'])
            return HttpResponse(options)
      

    context = {
        'local_help_circle' : True,
        'my_local_area_selected' : True
    }

    result = get_location_data(None,None,None)
    print(result)
    context[result['location']] = result['result']


    return render(request,'covid19helplineinfoapp/mylocalinfo.html',context=context)


def mylocalinfoform(request):
    print("submitting form")
    if request.method == 'POST':
        print("submitting form")
        form = LocalHelpInfoForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {}
    context['form'] = LocalHelpInfoForm()

    return render(request,'covid19helplineinfoapp/mylocalinfoform.html',context=context)
import io
def loaddata(request):
    loaddata = LoadDataModel.objects.all()[0]
    # print(loaddata.data)
    f = io.StringIO(loaddata.data)
    for line in f:
        # print(line.splitlines())
        val = line.splitlines()[0].split(',')
        print(val)
        state = val[0]
        phonenumber1 = val[1]        
        phonenumber2 = val[2] if len(val) == 3 else '+91-11-23978046'
        phonenumber3 = '+91-11-23978046' if len(val) == 3 else '' 
        LocalHelpInfo.objects.create(city='NA', country='India',state=state,helpline_phonenumber1=phonenumber1,helpline_phonenumber2=phonenumber2,helpline_phonenumber3=phonenumber3)
    return HttpResponse(200)
# ======================== END OF BIZ FUNCTIONALITY======================


@login_required
def profile(request):
    profile_instance = Profile.objects.filter(user__username=request.user)[0]
    context = {
        "username": request.user,
        "profile_pic_url": profile_instance.profile_pic.url,
    }
    return render(request, "covid19helplineinfoapp/profile.html", context)


@login_required
def help(request):
    profile_instance = Profile.objects.filter(user__username=request.user)[0]
    context = {
        "username": request.user,
        "profile_pic_url": profile_instance.profile_pic.url,
    }
    return render(request, "covid19helplineinfoapp/help.html", context)


######################################################
######################################################
######################################################

#                  Authentication

######################################################
######################################################
######################################################
def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            if form.is_valid():
                user = form.save()
                user.is_active = False
                user.save()
                print(request.POST)

                username = request.POST['username']
                country = request.POST['country']
                state = request.POST['state']
                district = request.POST['district']
                lng = request.POST['lng']
                lat = request.POST['lat']
                address = request.POST['address']
                help_type = request.POST['help_type']
                help_text = request.POST['help_text']
                
                profile_instance = Profile.objects.filter(user__username=request.POST['username'])[0]
                profile_instance.country = country
                profile_instance.state = state
                profile_instance.district = district
                profile_instance.lng = lng
                profile_instance.lat = lat
                profile_instance.address = address
                profile_instance.help_type = help_type
                profile_instance.help_text = help_text

                # profile_instance.set_location()

                profile_instance.save()

                current_site = get_current_site(request)
                subject = "Activate Your MySite Account"
                message = render_to_string(
                    "registration/account_activation_email.html",
                    {
                        "user": user,
                        "domain": current_site.domain,
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        # 'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                        "token": account_activation_token.make_token(user),
                    },
                )
                print("=============")
                print(user.pk)
                # print(urlsafe_base64_encode(force_bytes(user.pk)).decode('utf-8'))
                print(message)
                print(user.email)

                # user.email_user(subject, message)

                # ----------------
                email = EmailMessage(subject, message, to=[user.email])
                email.send()
                return redirect("account_activation_sent/")
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {"form": form,'GMAP_API_KEY': settings.GMAP_API_KEY})


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        print(uid)
        user = User.objects.get(pk=uid)
        print(user)
        print(token)
        print(account_activation_token.check_token(user, token))
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.profile.email_confirmed = True
            user.save()

covid19helplineinfoproject/covid19helplineinfoapp/templates/covid19helplineinfoapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Covid19 Helpline Info</title>
  <!-- Custom fonts for this template-->
  <link href="{% static 'admintheme/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="{% static 'admintheme/css/sb-admin-2.min.css'%}" rel="stylesheet">
  <style>
   
  </style>
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon ">
          <i class="fas fa-info-circle"></i>
        </div>
        <div class="sidebar-brand-text mx-3"><em>covid19helpline Info</em> <small> by Rebataur</small></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'covid19helplineinfoapp:home' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Administration
      </div>
      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link {% if not local_help_circle %}collapsed{% endif %}" href="#" data-toggle="collapse"
          data-target="#masterdata" aria-expanded="true" aria-controls="masterdata">
          <i class="fas fa-fw fa-cog"></i>
          <span>Local Info</span>
        </a>
        <div id="masterdata" class="collapse {% if local_help_circle %}show{% endif %}" aria-labelledby="headingTwo"
          data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Manage</h6>
            <a class="collapse-item {% if my_local_area_selected %}active{% endif %}"
              href="{% url 'covid19helplineinfoapp:mylocalinfo'%}">Local Help</a>
          
          </div>
        </div>
      </li>


    </ul>
    <!-- End of Sidebar -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>


       

        </nav>
        <!-- End of Topbar -->


        <!-- Javascript Deps -->
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'admintheme/vendor/jquery/jquery.min.js'%}"></script>
        <script src="{% static 'admintheme/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'admintheme/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'admintheme/js/sb-admin-2.min.js'%}"></script>

        <!-- Page level plugins -->
        <script src="{% static 'admintheme/vendor/chart.js/Chart.min.js'%}"></script>

        <script src="https://intercoolerjs.org/release/intercooler-1.2.3.min.js"></script>
        <script>
          $(document).ready(function () {




            // console.log('SSE ------------');
            // var source = new EventSource('/home/stream');
            // source.onmessage = function (e) {
            //   console.log(e.data);
            //   console.log('---------------');
            // };
          });
        </script>

        <input name="csrfmiddlewaretoken" type="hidden" value="{{ csrf_token }}" id="csrf" ic-global-include="#csrf">


        <!-- Content Wrapper -->
        {% block content %}{% endblock %}


      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span><a target="_blank" href="https://rebataur.com">Rebataur</a> 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="/accounts/logout">Logout</a>
        </div>
      </div>
    </div>
  </div>



</body>

</html>

covid19helplineinfoproject/covid19helplineinfoapp/templates/covid19helplineinfoapp/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <a href="/home">Home</a>
    <a href="/accounts/login">Login</a>
    <a href="/accounts/logout">Logout</a>
    <a href="/signup">Register</a>
</body>
</html>

covid19helplineinfoproject/covid19helplineinfoapp/templates/covid19helplineinfoapp/mylocalinfo.html
{% extends 'covid19helplineinfoapp/base.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">Local Help Info</li>
    </ol>
  </nav>

  <form method='GET'>
    <div class="form-group">
      <label for="exampleInputEmail1">Country</label>
      <select name="country"
        ic-post-to='{% url 'covid19helplineinfoapp:mylocalinfofilter' %}'
        ic-target='#state-select' class="custom-select">

        <option selected>Select One</option>
        {% for country in country %}

        <option value="{{country.country}}">{{country.country}}
        </option>
        {% endfor %}

      </select>
      <small id="emailHelp" class="form-text text-muted">Keep Typing and it will search</small>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">State</label>
      <select name="state" ic-post-to='{% url 'covid19helplineinfoapp:mylocalinfofilter' %}'
        ic-target='#city-select' class="custom-select" id="state-select">

      </select>
      <small id="emailHelp" class="form-text text-muted">Keep Typing and it will search</small>
    </div>
    <!-- <div class="form-group">
      <label for="exampleInputEmail1">City</label>
      <select name="city" class="custom-select" id="city-select">
      </select>
      <small id="emailHelp" class="form-text text-muted">Keep Typing and it will search</small>
    </div> -->
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'covid19helplineinfoapp:mylocalinfoform' %}" class="">Not Found Create Data</a>
  </form>

  {% endblock %}

covid19helplineinfoproject/covid19helplineinfoapp/templates/covid19helplineinfoapp/mylocalinfodetail.html
{% extends 'covid19helplineinfoapp/base.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">Local Help Info</li>
      <!-- <li class="breadcrumb-item active" aria-current="page"><a
              href="{% url 'covid19helplineinfoapp:mylocalinfo'   %}" class="">Manage</a></li> -->
    </ol>
  </nav>


  <table class="table stripe">

    <tr>
      <td>Location</td>
      <td>{{info.country}} - {{info.state}} - {{info.city}} - {{info.area}}</td>
    </tr>
    <tr>
      <td>Helpline Phonenumber 1</td>
      <td>{{info.helpline_phonenumber1}}</td>
    </tr>
    <tr>
      <td>Helpline Phonenumber 2</td>
      <td>{{info.helpline_phonenumber2}}</td>
    </tr>
    <tr>
      <td>Helpline Phonenumber 3</td>
      <td>{{info.helpline_phonenumber3}}</td>
    </tr>
    <tr>
      <td>Whatsapp Phonenumber</td>
      <td>{{info.helpline_whatsapp_phonenumber}}</td>
    </tr>
    <tr>
      <td>Helpline Email</td>
      <td>{{info.helpline_email}}</td>
    </tr>
    <tr>
      <td>Helcenter Address</td>
      <td>{{info.helpline_centre_address}}</td>
    </tr>
    <tr>
      <td>How to get there</td>
      <td>{{info.howto_get_there}}</td>
    </tr>
    <tr>
      <td>Other Instructions</td>
      <td>{{info.other_instructions}}</td>
    </tr>
    <tr>
      <td>Location</td>
      <td>{{info.other_instructions}}</td>
    </tr>
    <tr>
      <td>Map Location URL</td>
      <td>{{info.map_location_url}}</td>
    </tr>
    <tr>
      <td>Information Source</td>
      <td>{{info.info_source}}</td>

    </tr>
  </table>

  {% endblock %}

covid19helplineinfoproject/covid19helplineinfoapp/templates/covid19helplineinfoapp/mylocalinfoform.html
{% extends 'covid19helplineinfoapp/base.html' %}
{% block content %}
<style>
    p > label{
        width:200px;
    }
</style>
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">Local Help Info</li>
      <!-- <li class="breadcrumb-item active" aria-current="page"><a
              href="{% url 'covid19helplineinfoapp:mylocalinfo'   %}" class="">Manage</a></li> -->
    </ol>
  </nav>


<form method="POST" action="{% url 'covid19helplineinfoapp:mylocalinfoform' %}">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success" type="submit">Submit</button>
</form>

  {% endblock %}

covid19helplineinfoproject/covid19helplineinfoapp/templates/covid19helplineinfoapp/persondetails.html
{% extends 'covid19helplineinfoapp/base.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">Person Details</li>
      <!-- <li class="breadcrumb-item active" aria-current="page"><a
              href="{% url 'covid19helplineinfoapp:mylocalinfo'   %}" class="">Manage</a></li> -->
    </ol>
  </nav>


  <table class="table stripe">

    <tr>
      <td>Type</td>
      <td>{{profile_instance.help_type}}</td>
    </tr>
    <tr>
        <td>Help Text</td>
        <td>{{profile_instance.help_text}}</td>
      </tr>
      <tr>
        <td>Name</td>
        <td>{{profile_instance.user.first_name}} {{profile_instance.user.last_name}}</td>
      </tr>
      <tr>
        <td>Email</td>
        <td>{{profile_instance.user.email}}</td>
      </tr>

   
  </table>

  {% endblock %}